config/routes.rb
Rails.application.routes.draw do
  resources :commentaires
  resources :tags
  resources :blogs
  resources :users
  # resources :sessions, only: [:new, :create, :destroy] façon différentes d'écrire
  resources :sessions, only: %w[new create destroy]
  root "blogs#index"

  get 'signup', to: 'users#new', as: 'signup'
  get 'login', to: 'sessions#new', as: 'login'
  get 'logout', to: 'sessions#destroy', as: 'logout'
  get 'profile', to: 'users#profile', as: 'profile'

  namespace :admin do
    resources :commentaires
    resources :tags
    resources :blogs
    resources :users
  end

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/blog.rb
class Blog < ApplicationRecord
  belongs_to :user
  has_and_belongs_to_many :tags
  has_many :commentaires
end

app/controllers/admin/blogs_controller.rb
module Admin
  class BlogsController < AdminController
    before_action :set_blog, only: [:edit, :update, :destroy]
    before_action :set_users, only: [:new, :show, :edit, :update, :destroy]
    before_action :set_commentaire, only: [:new, :show, :edit, :update, :destroy]

    # GET /blogs
    # GET /blogs.json
    def index
      # @blogs = Blog.all
      @blogs = Blog.includes(:user).all
    end

    # GET /blogs/1
    # GET /blogs/1.json
    def show
      #@tags = @blog.tags
      #@tags = récupère tous les tags d'un blog
      @blog = Blog.includes(:tags).find(params[:id])
      @comments = @blog.commentaires.order(published_at: :desc)
      @comment = Commentaire.new
    end

    # GET /blogs/new
    def new
      @blog = Blog.new
    end

    # GET /blogs/1/edit
    def edit
    end

    # POST /blogs
    # POST /blogs.json
    def create
      @blog = Blog.new(blog_params)

      respond_to do |format|
        if @blog.save
          format.html { redirect_to @blog, notice: 'Blog was successfully created.' }
          format.json { render :show, status: :created, location: @blog }
        else
          format.html { render :new }
          format.json { render json: @blog.errors, status: :unprocessable_entity }
        end
      end
    end

    # PATCH/PUT /blogs/1
    # PATCH/PUT /blogs/1.json
    def update
      respond_to do |format|
        if @blog.update(blog_params)
          format.html { redirect_to @blog, notice: 'Blog was successfully updated.' }
          format.json { render :show, status: :ok, location: @blog }
        else
          format.html { render :edit }
          format.json { render json: @blog.errors, status: :unprocessable_entity }
        end
      end
    end

    # DELETE /blogs/1
    # DELETE /blogs/1.json
    def destroy
      @blog.destroy
      respond_to do |format|
        format.html { redirect_to blogs_url, notice: 'Blog was successfully destroyed.' }
        format.json { head :no_content }
      end
    end

    private
      # Use callbacks to share common setup or constraints between actions.
      def set_blog
        @blog = Blog.find(params[:id])
      end

      def set_users
        @users = User.all
      end
      
      def set_tag
        @tag = Tag.all
      end
      
      def set_commentaire
        @commentaire = Commentaire.all
      end
      
      # Only allow a list of trusted parameters through.
      def blog_params
        params.require(:blog).permit(:title, :content, :published_at, :draft, :user_id, tag_ids: [], commentaire_ids: [])
      end
  end
end

app/controllers/blogs_controller.rb
class BlogsController < ApplicationController
  before_action :set_blog, only: [:edit, :update, :destroy]
  before_action :set_users, only: [:new, :show, :edit, :update, :destroy]
  before_action :set_commentaire, only: [:new, :show, :edit, :update, :destroy]

  # GET /blogs
  # GET /blogs.json
  def index
    # @blogs = Blog.all
    @blogs = Blog.includes(:user).all
  end

  # GET /blogs/1
  # GET /blogs/1.json
  def show
    #@tags = @blog.tags
    #@tags = récupère tous les tags d'un blog
    @blog = Blog.includes(:tags).find(params[:id])
    @comments = @blog.commentaires.order(published_at: :desc)
    @comment = Commentaire.new
  end

  # GET /blogs/new
  def new
    @blog = Blog.new
  end

  # GET /blogs/1/edit
  def edit
  end

  # POST /blogs
  # POST /blogs.json
  def create
    @blog = Blog.new(blog_params)

    respond_to do |format|
      if @blog.save
        format.html { redirect_to @blog, notice: 'Blog was successfully created.' }
        format.json { render :show, status: :created, location: @blog }
      else
        format.html { render :new }
        format.json { render json: @blog.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /blogs/1
  # PATCH/PUT /blogs/1.json
  def update
    respond_to do |format|
      if @blog.update(blog_params)
        format.html { redirect_to @blog, notice: 'Blog was successfully updated.' }
        format.json { render :show, status: :ok, location: @blog }
      else
        format.html { render :edit }
        format.json { render json: @blog.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /blogs/1
  # DELETE /blogs/1.json
  def destroy
    @blog.destroy
    respond_to do |format|
      format.html { redirect_to blogs_url, notice: 'Blog was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_blog
      @blog = Blog.find(params[:id])
    end

    def set_users
      @users = User.all
    end
    
    def set_tag
      @tag = Tag.all
    end
    
    def set_commentaire
      @commentaire = Commentaire.all
    end
    
    # Only allow a list of trusted parameters through.
    def blog_params
      params.require(:blog).permit(:title, :content, :published_at, :draft, :user_id, tag_ids: [], commentaire_ids: [])
    end
end

app/helpers/blogs_helper.rb
module BlogsHelper
end

app/views/blogs/_form.html.erb
<%= form_with(model: blog, url: admin_blog_path, local: true) do |form| %>
  <% if blog.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(blog.errors.count, "error") %> prohibited this blog from being saved:</h2>

      <ul>
        <% blog.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :title %>
    <%= form.text_field :title %>
  </div>

  <div class="field">
    <%= form.label :content %>
    <%= form.text_area :content %>
  </div>

  <div class="field">
    <%= form.label :published_at %>
    <%= form.datetime_select :published_at %>
  </div>

  <div class="field">
    <%= form.label :draft %>
    <%= form.check_box :draft %>
  </div>

  <div class="field">
    <%= form.label :user_id %>
    <%= form.select :user_id, @users.collect {|a| [a.name, a.id]} %>
  </div>

  <div class="field">
    <%= form.label :tag_ids %>
    <%#= form.collection_check_boxes :tag_ids, Tag.order("name ASC").all, "id", :name, prompt: "Select an option", class: "form-control" %>
    <%= form.collection_select :tag_ids, Tag.order("name ASC").all, :id, :name, {prompt: "Select an option"}, {multiple: true, class: "form-control", size: '10'} %>

  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/blogs/_new_comment.html.erb
<p>
  <strong>Add comment:</strong>
</p>

<%= form_with(model: @comment, local: true) do |form| %>
  <% if @comment.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@comment.errors.count, "error") %> prohibited this commentaire from being saved:</h2>

      <ul>
        <% @comment.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

<div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :email %>
    <%= form.text_field :email %>
  </div>

  <div class="field">
    <%= form.label :content %>
    <%= form.text_area :content %>
  </div>

  <div class="field">
    <%= form.hidden_field :published_at, value: DateTime.current.to_s(:db)  %>
  </div>

  <div class="field">
    <%= form.hidden_field :blog_id, value: @blog.id%>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/blogs/edit.html.erb
<h1>Editing Blog</h1>

<%= render 'form', blog: @blog %>

<%= link_to 'Show', @blog %> |
<%= link_to 'Back', blogs_path %>

app/views/blogs/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Blogs</h1>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Content</th>
      <th>Published at</th>
      <% if current_user %>
        <th>Draft</th>
        <th>User ID</th>
      <% end %>
      <th>User Name</th>
      <th colspan="3">Options</th>
    </tr>
  </thead>

  <tbody>
    <% @blogs.each do |blog| %>
      <tr>
        <td><%= blog.title %></td>
        <td><%= truncate blog.content, length: 60 %></td>
        <td><%= blog.published_at %></td>
        <% if current_user %>
          <td><%= blog.draft %></td>
          <td><%= blog.user_id %></td>
        <% end %>
        <td><%= blog.user.name %> <a><%= link_to 'Profile', blog.user %></a></td>
        <td><%= link_to 'Show', blog %></td>
        <% if current_user %>
          <td><%= link_to 'Edit', edit_blog_path(blog) %></td>
          <td><%= link_to 'Destroy', blog, method: :delete, data: { confirm: 'Are you sure?' } %></td>
        <% end %>
      </tr>
    <% end %>
  </tbody>
</table>

<br>


<% if current_user %>
  <%= link_to 'New Blog', new_blog_path %>
<% end %>

app/views/blogs/new.html.erb
<h1>New Blog</h1>

<%= render 'form', blog: @blog %>

<%= link_to 'Back', blogs_path %>

app/views/blogs/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @blog.title %>
</p>

<p>
  <strong>Content:</strong>
  <%= @blog.content %>
</p>

<p>
  <strong>Published at:</strong>
  <%= @blog.published_at %>
</p>

<p>
  <strong>Draft:</strong>
  <%= @blog.draft %>
</p>

<p>
  <strong>User:</strong>
  <%= @blog.user.name %>
</p>

<% if @blog.tags.length > 0 %>
<p>
  <strong>Categories:</strong>
  <%= @blog.tags.map(&:name).join(', ') %>
  <%# Affiche le tableau des tags en séparant les valeurs par ", " %>
</p>
<% end %>

<p>
  <strong>Comments:</strong>
</p>
<% if @comments.length > 0 %>
  <table>
    <thead>
      <tr>
        <th>Name</th>
        <th>Comment</th>
        <th>Published at</th>
        <th colspan="2"></th>
      </tr>
    </thead>
    <tbody>
      <% @comments.each do |comment| %>
        <tr>
          <td><%= comment.name %></td>
          <td><%= truncate comment.content, length: 80 %></td>
          <td><%= comment.published_at %></td>
          <td><%= link_to 'Show', comment %></td>
          <% if current_user %>
            <td><%= link_to 'Destroy', comment, method: :delete, data: { confirm: 'Are you sure to delete this comment?' } %></td>
          <% end %>
        </tr>
      <% end %>
    </tbody>
  </table>
<% else %>
  <p>Pas de commentaires pour ce blog.</p>
<% end %>

<% if current_user %>
  <%= render 'new_comment', blog: @blog %>
  <%= link_to 'Edit', edit_blog_path(@blog) %> |
  <% end %>

<%= link_to 'Back', blogs_path %>