config/routes.rb
Rails.application.routes.draw do
  resources :commentaires
  resources :tags
  resources :blogs
  resources :users
  # resources :sessions, only: [:new, :create, :destroy] façon différentes d'écrire
  resources :sessions, only: %w[new create destroy]
  root "blogs#index"

  get 'signup', to: 'users#new', as: 'signup'
  get 'login', to: 'sessions#new', as: 'login'
  get 'logout', to: 'sessions#destroy', as: 'logout'
  get 'profile', to: 'users#profile', as: 'profile'

  namespace :admin do
    resources :commentaires
    resources :tags
    resources :blogs
    resources :users
  end

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/views/layouts/admin.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Admin / Myblog</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <link href="https://fonts.googleapis.com/css?family=Rubik:300,300i,400,400i,500,500i,700,700i,900,900i&display=swap" rel="stylesheet">

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body style="background-color: #c1c1c1;">
    <header>
        <nav>
          <ul>
      <% if current_user %>
            <li><%= link_to 'Admin Blogs', admin_blogs_path, class: 'link_nav' %></li>
            <li><%= link_to 'Users', admin_users_path, class: 'link_nav' %></li>
            <li><%= link_to 'Profile', profile_path, class: 'link_nav' %></li>
            <li><%= link_to 'Logout', logout_path, class: 'link_nav' %></li>
      <% else %>
            <li><%= link_to 'Blogs', blogs_url, class: 'link_nav' %></li>
            <li><%= link_to 'Profile', profile_path, class: 'link_nav' %></li>
            <li><%= link_to 'Login', login_path, class: 'link_nav' %></li>
      <% end %>
          </ul>
        </nav>
    </header>
  
    <%= yield %>
  </body>
</html>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Myblog</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <link href="https://fonts.googleapis.com/css?family=Rubik:300,300i,400,400i,500,500i,700,700i,900,900i&display=swap" rel="stylesheet">

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <header>
        <nav>
          <ul>
      <% if current_user %>
            <li><%= link_to 'Admin Blogs', admin_blogs_path, class: 'link_nav' %></li>
            <li><%= link_to 'Users', admin_users_path, class: 'link_nav' %></li>
            <li><%= link_to 'Profile', profile_path, class: 'link_nav' %></li>
            <li><%= link_to 'Logout', logout_path, class: 'link_nav' %></li>
      <% else %>
            <li><%= link_to 'Blogs', blogs_url, class: 'link_nav' %></li>
            <li><%= link_to 'Profile', profile_path, class: 'link_nav' %></li>
            <li><%= link_to 'Login', login_path, class: 'link_nav' %></li>
      <% end %>
          </ul>
        </nav>
    </header>
  
    <%= yield %>
  </body>
</html>